// countries.js\
export const countries = [
  { name: "Afghanistan", baseLifeExpectancy: 65 },
  { name: "Albania", baseLifeExpectancy: 78 },
  { name: "Algeria", baseLifeExpectancy: 76 },
  { name: "Angola", baseLifeExpectancy: 62 },
  { name: "Argentina", baseLifeExpectancy: 76 },
  { name: "Armenia", baseLifeExpectancy: 75 },
  { name: "Australia", baseLifeExpectancy: 83 },
  { name: "Austria", baseLifeExpectancy: 82 },
  { name: "Azerbaijan", baseLifeExpectancy: 73 },
  { name: "Bahrain", baseLifeExpectancy: 77 },
  { name: "Bangladesh", baseLifeExpectancy: 73 },
  { name: "Belarus", baseLifeExpectancy: 74 },
  { name: "Belgium", baseLifeExpectancy: 82 },
  { name: "Bhutan", baseLifeExpectancy: 72 },
  { name: "Bolivia", baseLifeExpectancy: 72 },
  { name: "Bosnia and Herzegovina", baseLifeExpectancy: 77 },
  { name: "Brazil", baseLifeExpectancy: 75 },
  { name: "Bulgaria", baseLifeExpectancy: 75 },
  { name: "Cambodia", baseLifeExpectancy: 70 },
  { name: "Cameroon", baseLifeExpectancy: 60 },
  { name: "Canada", baseLifeExpectancy: 82 },
  { name: "Chile", baseLifeExpectancy: 80 },
  { name: "China", baseLifeExpectancy: 77 },
  { name: "Colombia", baseLifeExpectancy: 77 },
  { name: "Costa Rica", baseLifeExpectancy: 80 },
  { name: "Croatia", baseLifeExpectancy: 78 },
  { name: "Cuba", baseLifeExpectancy: 79 },
  { name: "Czech Republic", baseLifeExpectancy: 79 },
  { name: "Denmark", baseLifeExpectancy: 81 },
  { name: "Dominican Republic", baseLifeExpectancy: 74 },
  { name: "Ecuador", baseLifeExpectancy: 77 },
  { name: "Egypt", baseLifeExpectancy: 73 },
  { name: "El Salvador", baseLifeExpectancy: 74 },
  { name: "Estonia", baseLifeExpectancy: 78 },
  { name: "Ethiopia", baseLifeExpectancy: 67 },
  { name: "Finland", baseLifeExpectancy: 82 },
  { name: "France", baseLifeExpectancy: 83 },
  { name: "Georgia", baseLifeExpectancy: 74 },
  { name: "Germany", baseLifeExpectancy: 81 },
  { name: "Ghana", baseLifeExpectancy: 64 },
  { name: "Greece", baseLifeExpectancy: 82 },
  { name: "Guatemala", baseLifeExpectancy: 74 },
  { name: "Haiti", baseLifeExpectancy: 64 },
  { name: "Honduras", baseLifeExpectancy: 75 },
  { name: "Hungary", baseLifeExpectancy: 76 },
  { name: "Iceland", baseLifeExpectancy: 83 },
  { name: "India", baseLifeExpectancy: 70 },
  { name: "Indonesia", baseLifeExpectancy: 72 },
  { name: "Iran", baseLifeExpectancy: 77 },
  { name: "Iraq", baseLifeExpectancy: 70 },
  { name: "Ireland", baseLifeExpectancy: 82 },
  { name: "Israel", baseLifeExpectancy: 83 },
  { name: "Italy", baseLifeExpectancy: 84 },
  { name: "Jamaica", baseLifeExpectancy: 75 },
  { name: "Japan", baseLifeExpectancy: 84 },
  { name: "Jordan", baseLifeExpectancy: 75 },
  { name: "Kazakhstan", baseLifeExpectancy: 73 },
  { name: "Kenya", baseLifeExpectancy: 66 },
  { name: "Kuwait", baseLifeExpectancy: 75 },
  { name: "Latvia", baseLifeExpectancy: 75 },
  { name: "Lebanon", baseLifeExpectancy: 79 },
  { name: "Libya", baseLifeExpectancy: 73 },
  { name: "Lithuania", baseLifeExpectancy: 76 },
  { name: "Luxembourg", baseLifeExpectancy: 82 },
  { name: "Malaysia", baseLifeExpectancy: 76 },
  { name: "Malta", baseLifeExpectancy: 83 },
  { name: "Mexico", baseLifeExpectancy: 75 },
  { name: "Moldova", baseLifeExpectancy: 72 },
  { name: "Mongolia", baseLifeExpectancy: 70 },
  { name: "Montenegro", baseLifeExpectancy: 77 },
  { name: "Morocco", baseLifeExpectancy: 77 },
  { name: "Myanmar", baseLifeExpectancy: 67 },
  { name: "Nepal", baseLifeExpectancy: 71 },
  { name: "Netherlands", baseLifeExpectancy: 82 },
  { name: "New Zealand", baseLifeExpectancy: 82 },
  { name: "Nicaragua", baseLifeExpectancy: 74 },
  { name: "Nigeria", baseLifeExpectancy: 54 },
  { name: "North Korea", baseLifeExpectancy: 72 },
  { name: "Norway", baseLifeExpectancy: 83 },
  { name: "Pakistan", baseLifeExpectancy: 67 },
  { name: "Panama", baseLifeExpectancy: 79 },
  { name: "Paraguay", baseLifeExpectancy: 74 },
  { name: "Peru", baseLifeExpectancy: 77 },
  { name: "Philippines", baseLifeExpectancy: 71 },
  { name: "Poland", baseLifeExpectancy: 78 },
  { name: "Portugal", baseLifeExpectancy: 82 },
  { name: "Qatar", baseLifeExpectancy: 80 },
  { name: "Romania", baseLifeExpectancy: 76 },
  { name: "Russia", baseLifeExpectancy: 72 },
  { name: "Saudi Arabia", baseLifeExpectancy: 75 },
  { name: "Serbia", baseLifeExpectancy: 76 },
  { name: "Singapore", baseLifeExpectancy: 83 },
  { name: "Slovakia", baseLifeExpectancy: 77 },
  { name: "Slovenia", baseLifeExpectancy: 81 },
  { name: "South Africa", baseLifeExpectancy: 65 },
  { name: "South Korea", baseLifeExpectancy: 83 },
  { name: "Spain", baseLifeExpectancy: 83 },
  { name: "Sri Lanka", baseLifeExpectancy: 77 },
  { name: "Sudan", baseLifeExpectancy: 66 },
  { name: "Sweden", baseLifeExpectancy: 83 },
  { name: "Switzerland", baseLifeExpectancy: 84 },
  { name: "Syria", baseLifeExpectancy: 72 },
  { name: "Taiwan", baseLifeExpectancy: 81 },
  { name: "Tanzania", baseLifeExpectancy: 66 },
  { name: "Thailand", baseLifeExpectancy: 77 },
  { name: "Tunisia", baseLifeExpectancy: 77 },
  { name: "Turkey", baseLifeExpectancy: 78 },
  { name: "Uganda", baseLifeExpectancy: 64 },
  { name: "Ukraine", baseLifeExpectancy: 72 },
  { name: "United Arab Emirates", baseLifeExpectancy: 78 },
  { name: "United Kingdom", baseLifeExpectancy: 81 },
  { name: "United States", baseLifeExpectancy: 77 },
  { name: "Uruguay", baseLifeExpectancy: 78 },
  { name: "Uzbekistan", baseLifeExpectancy: 72 },
  { name: "Venezuela", baseLifeExpectancy: 72 },
  { name: "Vietnam", baseLifeExpectancy: 76 },
  { name: "Yemen", baseLifeExpectancy: 66 },
  { name: "Zambia", baseLifeExpectancy: 64 },
  { name: "Zimbabwe", baseLifeExpectancy: 62 },
];
